
- name: install basic networking stuff
  yum: name={{ item }}
  with_items:
    - firewalld

- name: start firewalld
  service: name=firewalld state=started enabled=true

- name: open ssh port
  firewalld:
    service: ssh
    state: enabled
    permanent: true
    immediate: true
  notify:
    - restart firewalld

