- hosts: vps3
  vars:
    app:
      name: ciptn-hook
      repo: https://github.com/ps-aux/ciptn-hook.git
    web:
      name: ci
      port: 3100
      https: false #TODO why default val is not taken from the web role ??

  roles:
      - basic
      - tools
      - web
      - nodejs-app
