- hosts: vps3
  vars:
    app:
      name: lunchgator
    web_name: api.{{ app.name }}
    web:
      name: '{{ web_name }}'
      port: 8080
      https: true
      cert:
        path: /etc/letsencrypt/live/{{ web_name }}.absolutne.pro/cert.pem
        key_path: /etc/letsencrypt/live/{{ web_name }}.absolutne.pro/privkey.pem
    db:
      name: '{{ app.name }}'
      user: '{{ app.name }}'
      pass: '{{ lookup("password", "/tmp/passwordfile chars=ascii_letters") }}'
      interfaces: [ 'localhost', '172.17.0.1'] #Docker
    env:
      LUNCHGATOR_DB_JDBC_URL: jdbc:postgresql://172.17.0.1:5432/{{ db.name }}
      LUNCHGATOR_DB_USER: '{{ db.user }}'
      LUNCHGATOR_DB_PASS: '{{ db.pass }}'
      LUNCHGATOR_PORT: '{{ web.port }}'
  roles:
      - basic
      - tools
      - conf-file
      - docker
      - web
      - database
      - spring-boot
