- hosts: vps3
  vars:
    app:
      name: lunchgator
    web:
      name: api.{{ app.name }}
      port: 8080
    db:
      name: '{{ app.name }}'
      user: '{{ app.name }}'
      interfaces: [ 'localhost', '172.17.0.1'] #Docker
  roles:
      - basic
      - tools
      - docker
      - web
      - database
      - spring-boot
