- hosts: vps3
  vars:
    app:
      name: lunchgator
    db_name: '{{ app.name }}'
    db_user: '{{ app.name }}'
    db_ifs: [ 'localhost', '172.17.0.1'] #Docker
  roles:
      - basic
      - tools
      - docker
      - database
      - spring-boot
