- hosts: vps3
  vars:
    app:
      name: lunchgator
    web:
      name: '{{ app.name }}'
      port: 8080
    db:
      user: '{{ app.name }}'
      intefaces: [ 'localhost', '172.17.0.1'] #Docker
  roles:
#      - basic
#      - tools
#      - docker
      - web
      - database
      - spring-boot
