- name: create scraping dir
  file: path=/opt/scraping state=directory
  register: scraping_dir_created


- name: download phantomjs
  unarchive:
    src: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
    dest: /opt/scraping
    remote_src: True
  when: scraping_dir_created|success
  register: phantomjs_downloaded

- name: install fontconfig
  yum: pkg=fontconfig state=installed update_cache=true
  register: fontconfig_installed

- name: setup phantomjs env vars
  template: src=env.sh.j2 dest=/etc/profile.d/phantomjs-env.sh

