---
  - name: checkout ciptn-hook from Github
    git:
      repo: '{{ app.repo }}'
      dest: '{{ dir_path }}'

  - name: install node dependencies
    npm: path={{dir_path}}

  - name: create systemd service file
    template:
      src: systemd-service.j2
      dest: /etc/systemd/system/{{ app.name }}.service

  - name: daemon-reload & restart systemd service
    systemd:
      state: restarted
      daemon_reload: yes
      name: '{{ app.name }}'
      enabled: True

