---
- name: add jenkins repo
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: import jenkins rpm key
  rpm_key:
    state: present
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: install jenkins
  yum: pkg=jenkins state=installed update_cache=true

- name: start jenkins service
  service: name=jenkins state=started enabled=true



