---
- name: install Nginx
  yum:
    name: nginx
    state: present

- name: setup nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: create sites conf dir
  file:
    path: /etc/nginx/sites-available
    state: directory

- name: setup root site
  template: src=sites/root.j2 dest=/etc/nginx/sites-available/root

# If getting 'connect() to 127.0.0.1:some-port failed (13: Permission denied) while connecting to upstream'
# Then running setsebool -P httpd_can_network_connect 1 should help


- name: start Nginx
  service:
    name: nginx
    state: started

- name: open web port
  firewalld:
    zone: public
    port: '{{web_port}}/tcp'
    state: enabled
    permanent: true
    immediate: true
