---
- include: nginx.yml

- name: open http port
  firewalld:
    zone: public
    port: '80/tcp'
    state: enabled
    permanent: true
    immediate: true

- name: open https port
  firewalld:
    zone: public
    port: '443/tcp'
    state: enabled
    permanent: true
    immediate: true
  when: web.https
